language: shell
dist: stretch

before_install:
  - sudo -H apt update
  - sudo -H apt install -y git python3.5
  - sudo -H python3 -m pip install --upgrade pip

deploy:
  provider: script
  script: sudo -H bash ./install.sh
  on:
    branch: master
