language: shell
dist: stretch

before_install:
  - sudo apt update
  - sudo apt install -y git python3.5
  - sudo pip install --upgrade pip

deploy:
  provider: script
  script: sudo -H bash ./install.sh
  on:
    branch: master
